//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klevtsov_Zakharov
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportRoutes
    {
        public int RoutesId { get; set; }
        public int AiportsId { get; set; }
        public int AirportId { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
