//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klevtsov_Zakharov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User05Entities5 : DbContext
    {
        public User05Entities5()
            : base("name=User05Entities5")
        {
        }
        private static User05Entities5 _context = new User05Entities5();

        public static User05Entities5 GetContext()
        {
            if (_context == null)
                _context = new User05Entities5();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<AirportRoutes> AirportRoutes { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Amenties> Amenties { get; set; }
        public virtual DbSet<AmentiesTickets> AmentiesTickets { get; set; }
        public virtual DbSet<CabinTypes> CabinTypes { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserssInfo> UserssInfo { get; set; }
    }
}
